# Generated by Django 3.1.2 on 2024-07-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240628_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_cliente', models.TextField()),
                ('comprobante', models.FileField(upload_to='comprobantes/')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.orden')),
            ],
        ),
    ]
