# Generated by Django 3.1.2 on 2024-07-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='core.orden'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='datos_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.orden')),
            ],
        ),
    ]
